### ISSUE TITLE
Icons and Logos

### ISSUE THREAD

**Issue by matthewwaldeck** [Gediren/AstroBlaster#3]
By default, GameMaker uses it's own logos in all fresh games. Totally fine, but I wonder if I could use an AI image generator to come up with a great icon for this game.

**Comment by Gediren** [comment]
<p>See wiki page "The Quest for a Logo", one has been found. See below. All iterations can be found in the repo files under the "icons" folder.</p>

![AstroBlaster_v6](https://github.com/Gediren/AstroBlaster/assets/8987013/c657203f-0c25-462d-a72c-2eeb28e4e02b)

**Comment by matthewwaldeck** [comment]
<p>See wiki page "The Quest for a Logo", one has been found. See below. All iterations can be found in the repo files under the "icons" folder.</p>

![AstroBlaster_v6](https://github.com/Gediren/AstroBlaster/assets/8987013/c657203f-0c25-462d-a72c-2eeb28e4e02b)
